branch-defaults:
  default:
    environment: Grantyourrequest-env
environment-defaults:
  Grantyourrequest-env:
    branch: null
    repository: null
global:
  application_name: grantyourrequest
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Python 3.4 running
    on 64bit Amazon Linux/2.5.2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
